/**
 * Mock data for fertilizer pages
 */

export interface ApplicationRecord {
  id: string;
  date: string;
  field: string;
  type: 'Chemical' | 'Slurry';
  product: string;
  rate: string;
  nValue: number;
}

export interface HarvestRecord {
  id: string;
  date: string;
  field: string;
  type: 'Silage' | 'Grazing' | 'Bale';
  yield: string;
  nValue: number;
}

export interface SoilTestRecord {
  id: string;
  date: string;
  field: string;
  nMinRange: string;
  scenario: 'Pessimistic' | 'Medium' | 'Optimistic';
  nValue: number;
}

export const MOCK_APPLICATIONS: ApplicationRecord[] = [
  {
    id: '1',
    date: '15/03/2024',
    field: 'North Field',
    type: 'Chemical',
    product: 'CAN',
    rate: '200 kg/ha',
    nValue: 54.0,
  },
  {
    id: '2',
    date: '10/04/2024',
    field: 'North Field',
    type: 'Slurry',
    product: 'Cattle Slurry',
    rate: '30 m³/ha',
    nValue: 54.0,
  },
  {
    id: '3',
    date: '15/05/2024',
    field: 'North Field',
    type: 'Chemical',
    product: 'Urea',
    rate: '120 kg/ha',
    nValue: 55.2,
  },
  {
    id: '4',
    date: '20/03/2024',
    field: 'South Paddock',
    type: 'Chemical',
    product: 'CAN',
    rate: '180 kg/ha',
    nValue: 48.6,
  },
  {
    id: '5',
    date: '25/04/2024',
    field: 'South Paddock',
    type: 'Slurry',
    product: 'Pig Slurry',
    rate: '25 m³/ha',
    nValue: 45.0,
  },
  {
    id: '6',
    date: '05/04/2024',
    field: 'East Meadow',
    type: 'Chemical',
    product: '18-6-12',
    rate: '250 kg/ha',
    nValue: 45.0,
  },
  {
    id: '7',
    date: '10/05/2024',
    field: 'East Meadow',
    type: 'Chemical',
    product: 'Urea',
    rate: '100 kg/ha',
    nValue: 46.0,
  },
  {
    id: '8',
    date: '25/03/2024',
    field: 'West Slope',
    type: 'Slurry',
    product: 'Pig Slurry',
    rate: '35 m³/ha',
    nValue: 63.0,
  },
  {
    id: '9',
    date: '01/05/2024',
    field: 'West Slope',
    type: 'Chemical',
    product: 'CAN',
    rate: '160 kg/ha',
    nValue: 43.2,
  },
  {
    id: '10',
    date: '12/04/2024',
    field: 'River Bottom',
    type: 'Chemical',
    product: 'Urea',
    rate: '140 kg/ha',
    nValue: 64.4,
  },
  {
    id: '11',
    date: '18/05/2024',
    field: 'North Field',
    type: 'Slurry',
    product: 'Cattle Slurry',
    rate: '28 m³/ha',
    nValue: 50.4,
  },
  {
    id: '12',
    date: '22/06/2024',
    field: 'South Paddock',
    type: 'Chemical',
    product: 'CAN',
    rate: '190 kg/ha',
    nValue: 51.3,
  },
  {
    id: '13',
    date: '08/07/2024',
    field: 'East Meadow',
    type: 'Slurry',
    product: 'Pig Slurry',
    rate: '32 m³/ha',
    nValue: 57.6,
  },
  {
    id: '14',
    date: '15/08/2024',
    field: 'West Slope',
    type: 'Chemical',
    product: 'Urea',
    rate: '110 kg/ha',
    nValue: 50.6,
  },
  {
    id: '15',
    date: '20/09/2024',
    field: 'River Bottom',
    type: 'Chemical',
    product: '18-6-12',
    rate: '240 kg/ha',
    nValue: 43.2,
  },
  {
    id: '16',
    date: '05/10/2024',
    field: 'North Field',
    type: 'Slurry',
    product: 'Cattle Slurry',
    rate: '26 m³/ha',
    nValue: 46.8,
  },
  {
    id: '17',
    date: '12/11/2024',
    field: 'South Paddock',
    type: 'Chemical',
    product: 'CAN',
    rate: '175 kg/ha',
    nValue: 47.25,
  },
  {
    id: '18',
    date: '18/12/2024',
    field: 'East Meadow',
    type: 'Chemical',
    product: 'Urea',
    rate: '130 kg/ha',
    nValue: 59.8,
  },
  {
    id: '19',
    date: '25/01/2025',
    field: 'West Slope',
    type: 'Slurry',
    product: 'Pig Slurry',
    rate: '30 m³/ha',
    nValue: 54.0,
  },
  {
    id: '20',
    date: '02/02/2025',
    field: 'River Bottom',
    type: 'Chemical',
    product: 'CAN',
    rate: '210 kg/ha',
    nValue: 56.7,
  },
  {
    id: '21',
    date: '10/03/2025',
    field: 'North Field',
    type: 'Chemical',
    product: 'Urea',
    rate: '115 kg/ha',
    nValue: 52.9,
  },
  {
    id: '22',
    date: '17/04/2025',
    field: 'South Paddock',
    type: 'Slurry',
    product: 'Cattle Slurry',
    rate: '29 m³/ha',
    nValue: 52.2,
  },
  {
    id: '23',
    date: '24/05/2025',
    field: 'East Meadow',
    type: 'Chemical',
    product: '18-6-12',
    rate: '230 kg/ha',
    nValue: 41.4,
  },
  {
    id: '24',
    date: '01/06/2025',
    field: 'West Slope',
    type: 'Chemical',
    product: 'CAN',
    rate: '185 kg/ha',
    nValue: 49.95,
  },
  {
    id: '25',
    date: '08/07/2025',
    field: 'River Bottom',
    type: 'Slurry',
    product: 'Pig Slurry',
    rate: '33 m³/ha',
    nValue: 59.4,
  },
  {
    id: '26',
    date: '15/08/2025',
    field: 'North Field',
    type: 'Chemical',
    product: 'Urea',
    rate: '125 kg/ha',
    nValue: 57.5,
  },
  {
    id: '27',
    date: '22/09/2025',
    field: 'South Paddock',
    type: 'Chemical',
    product: 'CAN',
    rate: '195 kg/ha',
    nValue: 52.65,
  },
  {
    id: '28',
    date: '29/10/2025',
    field: 'East Meadow',
    type: 'Slurry',
    product: 'Cattle Slurry',
    rate: '27 m³/ha',
    nValue: 48.6,
  },
  {
    id: '29',
    date: '05/11/2025',
    field: 'West Slope',
    type: 'Chemical',
    product: 'Urea',
    rate: '105 kg/ha',
    nValue: 48.3,
  },
  {
    id: '30',
    date: '12/12/2025',
    field: 'River Bottom',
    type: 'Chemical',
    product: '18-6-12',
    rate: '220 kg/ha',
    nValue: 39.6,
  },
  {
    id: '31',
    date: '19/01/2026',
    field: 'North Field',
    type: 'Slurry',
    product: 'Pig Slurry',
    rate: '31 m³/ha',
    nValue: 55.8,
  },
];

export const MOCK_HARVESTS: HarvestRecord[] = [
  {
    id: '1',
    date: '20/06/2024',
    field: 'North Field',
    type: 'Silage',
    yield: '22 t/ha',
    nValue: 99.0,
  },
  {
    id: '2',
    date: '15/08/2024',
    field: 'North Field',
    type: 'Silage',
    yield: '20 t/ha',
    nValue: 90.0,
  },
  {
    id: '3',
    date: '01/06/2024',
    field: 'South Paddock',
    type: 'Silage',
    yield: '18 t/ha',
    nValue: 81.0,
  },
  {
    id: '4',
    date: '10/09/2024',
    field: 'South Paddock',
    type: 'Grazing',
    yield: '3 t DM/ha',
    nValue: 57.6,
  },
  {
    id: '5',
    date: '25/05/2024',
    field: 'East Meadow',
    type: 'Silage',
    yield: '18 t/ha',
    nValue: 81.0,
  },
  {
    id: '6',
    date: '20/07/2024',
    field: 'East Meadow',
    type: 'Bale',
    yield: '12 t/ha',
    nValue: 43.2,
  },
  {
    id: '7',
    date: '10/06/2024',
    field: 'West Slope',
    type: 'Silage',
    yield: '18 t/ha',
    nValue: 81.0,
  },
  {
    id: '8',
    date: '05/09/2024',
    field: 'West Slope',
    type: 'Grazing',
    yield: '2.5 t DM/ha',
    nValue: 48.0,
  },
  {
    id: '9',
    date: '01/07/2024',
    field: 'River Bottom',
    type: 'Silage',
    yield: '20 t/ha',
    nValue: 90.0,
  },
  {
    id: '10',
    date: '15/10/2024',
    field: 'North Field',
    type: 'Grazing',
    yield: '2.8 t DM/ha',
    nValue: 53.76,
  },
  {
    id: '11',
    date: '28/11/2024',
    field: 'South Paddock',
    type: 'Bale',
    yield: '11 t/ha',
    nValue: 39.6,
  },
  {
    id: '12',
    date: '10/12/2024',
    field: 'East Meadow',
    type: 'Silage',
    yield: '19 t/ha',
    nValue: 85.5,
  },
  {
    id: '13',
    date: '22/01/2025',
    field: 'West Slope',
    type: 'Grazing',
    yield: '3.2 t DM/ha',
    nValue: 61.44,
  },
  {
    id: '14',
    date: '05/02/2025',
    field: 'River Bottom',
    type: 'Silage',
    yield: '21 t/ha',
    nValue: 94.5,
  },
  {
    id: '15',
    date: '18/03/2025',
    field: 'North Field',
    type: 'Bale',
    yield: '13 t/ha',
    nValue: 46.8,
  },
  {
    id: '16',
    date: '30/04/2025',
    field: 'South Paddock',
    type: 'Silage',
    yield: '17 t/ha',
    nValue: 76.5,
  },
  {
    id: '17',
    date: '12/05/2025',
    field: 'East Meadow',
    type: 'Grazing',
    yield: '2.6 t DM/ha',
    nValue: 49.92,
  },
  {
    id: '18',
    date: '25/06/2025',
    field: 'West Slope',
    type: 'Silage',
    yield: '18 t/ha',
    nValue: 81.0,
  },
  {
    id: '19',
    date: '08/07/2025',
    field: 'River Bottom',
    type: 'Bale',
    yield: '14 t/ha',
    nValue: 50.4,
  },
  {
    id: '20',
    date: '20/08/2025',
    field: 'North Field',
    type: 'Silage',
    yield: '20 t/ha',
    nValue: 90.0,
  },
  {
    id: '21',
    date: '02/09/2025',
    field: 'South Paddock',
    type: 'Grazing',
    yield: '3.0 t DM/ha',
    nValue: 57.6,
  },
  {
    id: '22',
    date: '15/10/2025',
    field: 'East Meadow',
    type: 'Silage',
    yield: '19 t/ha',
    nValue: 85.5,
  },
  {
    id: '23',
    date: '28/11/2025',
    field: 'West Slope',
    type: 'Bale',
    yield: '12 t/ha',
    nValue: 43.2,
  },
  {
    id: '24',
    date: '10/12/2025',
    field: 'River Bottom',
    type: 'Grazing',
    yield: '2.7 t DM/ha',
    nValue: 51.84,
  },
  {
    id: '25',
    date: '22/01/2026',
    field: 'North Field',
    type: 'Silage',
    yield: '21 t/ha',
    nValue: 94.5,
  },
  {
    id: '26',
    date: '05/02/2026',
    field: 'South Paddock',
    type: 'Silage',
    yield: '18 t/ha',
    nValue: 81.0,
  },
  {
    id: '27',
    date: '18/03/2026',
    field: 'East Meadow',
    type: 'Bale',
    yield: '11 t/ha',
    nValue: 39.6,
  },
  {
    id: '28',
    date: '30/04/2026',
    field: 'West Slope',
    type: 'Grazing',
    yield: '3.1 t DM/ha',
    nValue: 59.52,
  },
  {
    id: '29',
    date: '12/05/2026',
    field: 'River Bottom',
    type: 'Silage',
    yield: '20 t/ha',
    nValue: 90.0,
  },
  {
    id: '30',
    date: '25/06/2026',
    field: 'North Field',
    type: 'Bale',
    yield: '13 t/ha',
    nValue: 46.8,
  },
  {
    id: '31',
    date: '08/07/2026',
    field: 'South Paddock',
    type: 'Silage',
    yield: '17 t/ha',
    nValue: 76.5,
  },
];

export const MOCK_SOIL_TESTS: SoilTestRecord[] = [
  {
    id: '1',
    date: '15/02/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Medium',
    nValue: 45.0,
  },
  {
    id: '2',
    date: '20/02/2024',
    field: 'South Paddock',
    nMinRange: '25 - 45 kg/ha',
    scenario: 'Optimistic',
    nValue: 45.0,
  },
  {
    id: '3',
    date: '10/02/2024',
    field: 'East Meadow',
    nMinRange: '30 - 50 kg/ha',
    scenario: 'Pessimistic',
    nValue: 30.0,
  },
  {
    id: '4',
    date: '25/02/2024',
    field: 'West Slope',
    nMinRange: '20 - 40 kg/ha',
    scenario: 'Medium',
    nValue: 30.0,
  },
  {
    id: '5',
    date: '18/02/2024',
    field: 'River Bottom',
    nMinRange: '40 - 60 kg/ha',
    scenario: 'Medium',
    nValue: 50.0,
  },
  {
    id: '6',
    date: '12/02/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Optimistic',
    nValue: 50.0,
  },
  {
    id: '7',
    date: '28/02/2024',
    field: 'South Paddock',
    nMinRange: '25 - 45 kg/ha',
    scenario: 'Medium',
    nValue: 35.0,
  },
  {
    id: '8',
    date: '05/03/2024',
    field: 'East Meadow',
    nMinRange: '30 - 50 kg/ha',
    scenario: 'Medium',
    nValue: 40.0,
  },
  {
    id: '9',
    date: '14/03/2024',
    field: 'West Slope',
    nMinRange: '20 - 40 kg/ha',
    scenario: 'Pessimistic',
    nValue: 25.0,
  },
  {
    id: '10',
    date: '22/03/2024',
    field: 'River Bottom',
    nMinRange: '40 - 60 kg/ha',
    scenario: 'Optimistic',
    nValue: 55.0,
  },
  {
    id: '11',
    date: '08/04/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Medium',
    nValue: 45.0,
  },
  {
    id: '12',
    date: '17/04/2024',
    field: 'South Paddock',
    nMinRange: '25 - 45 kg/ha',
    scenario: 'Pessimistic',
    nValue: 30.0,
  },
  {
    id: '13',
    date: '03/05/2024',
    field: 'East Meadow',
    nMinRange: '30 - 50 kg/ha',
    scenario: 'Optimistic',
    nValue: 48.0,
  },
  {
    id: '14',
    date: '11/05/2024',
    field: 'West Slope',
    nMinRange: '20 - 40 kg/ha',
    scenario: 'Medium',
    nValue: 30.0,
  },
  {
    id: '15',
    date: '19/05/2024',
    field: 'River Bottom',
    nMinRange: '40 - 60 kg/ha',
    scenario: 'Medium',
    nValue: 50.0,
  },
  {
    id: '16',
    date: '27/05/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Optimistic',
    nValue: 52.0,
  },
  {
    id: '17',
    date: '06/06/2024',
    field: 'South Paddock',
    nMinRange: '25 - 45 kg/ha',
    scenario: 'Medium',
    nValue: 35.0,
  },
  {
    id: '18',
    date: '15/06/2024',
    field: 'East Meadow',
    nMinRange: '30 - 50 kg/ha',
    scenario: 'Pessimistic',
    nValue: 32.0,
  },
  {
    id: '19',
    date: '23/06/2024',
    field: 'West Slope',
    nMinRange: '20 - 40 kg/ha',
    scenario: 'Optimistic',
    nValue: 38.0,
  },
  {
    id: '20',
    date: '01/07/2024',
    field: 'River Bottom',
    nMinRange: '40 - 60 kg/ha',
    scenario: 'Medium',
    nValue: 50.0,
  },
  {
    id: '21',
    date: '09/07/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Medium',
    nValue: 45.0,
  },
  {
    id: '22',
    date: '18/07/2024',
    field: 'South Paddock',
    nMinRange: '25 - 45 kg/ha',
    scenario: 'Optimistic',
    nValue: 42.0,
  },
  {
    id: '23',
    date: '26/07/2024',
    field: 'East Meadow',
    nMinRange: '30 - 50 kg/ha',
    scenario: 'Medium',
    nValue: 40.0,
  },
  {
    id: '24',
    date: '04/08/2024',
    field: 'West Slope',
    nMinRange: '20 - 40 kg/ha',
    scenario: 'Pessimistic',
    nValue: 28.0,
  },
  {
    id: '25',
    date: '13/08/2024',
    field: 'River Bottom',
    nMinRange: '40 - 60 kg/ha',
    scenario: 'Optimistic',
    nValue: 58.0,
  },
  {
    id: '26',
    date: '21/08/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Medium',
    nValue: 45.0,
  },
  {
    id: '27',
    date: '29/08/2024',
    field: 'South Paddock',
    nMinRange: '25 - 45 kg/ha',
    scenario: 'Medium',
    nValue: 35.0,
  },
  {
    id: '28',
    date: '07/09/2024',
    field: 'East Meadow',
    nMinRange: '30 - 50 kg/ha',
    scenario: 'Optimistic',
    nValue: 47.0,
  },
  {
    id: '29',
    date: '16/09/2024',
    field: 'West Slope',
    nMinRange: '20 - 40 kg/ha',
    scenario: 'Pessimistic',
    nValue: 22.0,
  },
  {
    id: '30',
    date: '24/09/2024',
    field: 'River Bottom',
    nMinRange: '40 - 60 kg/ha',
    scenario: 'Medium',
    nValue: 50.0,
  },
  {
    id: '31',
    date: '02/10/2024',
    field: 'North Field',
    nMinRange: '35 - 55 kg/ha',
    scenario: 'Optimistic',
    nValue: 53.0,
  },
];

export const APPLICATION_TYPE_OPTIONS = [
  { value: 'chemical', label: 'Chemical' },
  { value: 'slurry', label: 'Slurry' },
];

export const PRODUCT_OPTIONS = [
  { value: 'can-27', label: 'CAN (27% N)' },
  { value: 'urea-46', label: 'Urea (46% N)' },
  { value: '18-6-12', label: '18-6-12 (18% N)' },
  { value: 'cattle-slurry', label: 'Cattle Slurry' },
  { value: 'pig-slurry', label: 'Pig Slurry' },
];

export const HARVEST_TYPE_OPTIONS = [
  { value: 'silage', label: 'Silage Cut' },
  { value: 'grazing', label: 'Grazing' },
  { value: 'bale', label: 'Bale/Hay' },
];

export const SCENARIO_OPTIONS = [
  { value: 'pessimistic', label: 'Pessimistic' },
  { value: 'medium', label: 'Medium' },
  { value: 'optimistic', label: 'Optimistic' },
];
