export const getPostalCodeLabel = (countryName?: string): string => {
  if (!countryName) return 'Postal Code';

  const postalCodeLabels: Record<string, string> = {
    'United States': 'ZIP Code',
    USA: 'ZIP Code',
    US: 'ZIP Code',
    Ireland: 'Eircode',
    India: 'PIN Code',
    Brazil: 'CEP',
    Canada: 'Postal Code',
    'United Kingdom': 'Postcode',
    UK: 'Postcode',
    Australia: 'Postcode',
    'New Zealand': 'Postcode',
    'South Africa': 'Postal Code',
    Netherlands: 'Postcode',
    Belgium: 'Postcode',
    Luxembourg: 'Postcode',
    Switzerland: 'Postcode',
    Austria: 'Postcode',
    Germany: 'Postcode',
    Denmark: 'Postcode',
    Norway: 'Postcode',
    Sweden: 'Postcode',
    Finland: 'Postcode',
    Iceland: 'Postcode',
    Poland: 'Postcode',
    'Czech Republic': 'Postcode',
    Slovakia: 'Postcode',
    Hungary: 'Postcode',
    Romania: 'Postcode',
    Bulgaria: 'Postcode',
    Greece: 'Postcode',
    Portugal: 'Postcode',
    Spain: 'Postcode',
    Italy: 'Postcode',
    France: 'Postcode',
    Monaco: 'Postcode',
    Liechtenstein: 'Postcode',
    'San Marino': 'Postcode',
    'Vatican City': 'Postcode',
    Malta: 'Postcode',
    Cyprus: 'Postcode',
    Slovenia: 'Postcode',
    Croatia: 'Postcode',
    'Bosnia and Herzegovina': 'Postcode',
    Serbia: 'Postcode',
    Montenegro: 'Postcode',
    'North Macedonia': 'Postcode',
    Albania: 'Postcode',
    Kosovo: 'Postcode',
    Moldova: 'Postcode',
    Georgia: 'Postcode',
    Armenia: 'Postcode',
    Azerbaijan: 'Postcode',
    Kazakhstan: 'Postcode',
    Uzbekistan: 'Postcode',
    Turkmenistan: 'Postcode',
    Kyrgyzstan: 'Postcode',
    Tajikistan: 'Postcode',
    Afghanistan: 'Postcode',
    Pakistan: 'Postcode',
    Nepal: 'Postcode',
    Bhutan: 'Postcode',
    Bangladesh: 'Postcode',
    'Sri Lanka': 'Postcode',
    Maldives: 'Postcode',
    Mongolia: 'Postcode',
    'North Korea': 'Postcode',
    'South Korea': 'Postcode',
    Taiwan: 'Postcode',
    'Hong Kong': 'Postcode',
    Macau: 'Postcode',
    Japan: 'Postcode',
    China: 'Postcode',
    Israel: 'Postcode',
    Palestine: 'Postcode',
    Jordan: 'Postcode',
    Lebanon: 'Postcode',
    Syria: 'Postcode',
    Iraq: 'Postcode',
    Iran: 'Postcode',
    Kuwait: 'Postcode',
    'Saudi Arabia': 'Postcode',
    Bahrain: 'Postcode',
    Qatar: 'Postcode',
    'United Arab Emirates': 'Postcode',
    Oman: 'Postcode',
    Yemen: 'Postcode',
    Egypt: 'Postcode',
    Libya: 'Postcode',
    Tunisia: 'Postcode',
    Algeria: 'Postcode',
    Morocco: 'Postcode',
    'Western Sahara': 'Postcode',
    Mauritania: 'Postcode',
    Mali: 'Postcode',
    Niger: 'Postcode',
    Chad: 'Postcode',
    Sudan: 'Postcode',
    'South Sudan': 'Postcode',
    Ethiopia: 'Postcode',
    Eritrea: 'Postcode',
    Djibouti: 'Postcode',
    Somalia: 'Postcode',
    Uganda: 'Postcode',
    Tanzania: 'Postcode',
    Rwanda: 'Postcode',
    Burundi: 'Postcode',
    'Democratic Republic of the Congo': 'Postcode',
    'Republic of the Congo': 'Postcode',
    'Central African Republic': 'Postcode',
    Cameroon: 'Postcode',
    Gabon: 'Postcode',
    'Equatorial Guinea': 'Postcode',
    'São Tomé and Príncipe': 'Postcode',
    Angola: 'Postcode',
    Zambia: 'Postcode',
    Zimbabwe: 'Postcode',
    Botswana: 'Postcode',
    Namibia: 'Postcode',
    Lesotho: 'Postcode',
    Eswatini: 'Postcode',
    Madagascar: 'Postcode',
    Mauritius: 'Postcode',
    Seychelles: 'Postcode',
    Comoros: 'Postcode',
    Mayotte: 'Postcode',
    Réunion: 'Postcode',
    'Cape Verde': 'Postcode',
    'Guinea-Bissau': 'Postcode',
    Guinea: 'Postcode',
    'Sierra Leone': 'Postcode',
    Liberia: 'Postcode',
    "Côte d'Ivoire": 'Postcode',
    Ghana: 'Postcode',
    Togo: 'Postcode',
    Benin: 'Postcode',
    'Burkina Faso': 'Postcode',
    Gambia: 'Postcode',
    Senegal: 'Postcode',
    Mexico: 'Postcode',
    Argentina: 'Postcode',
    Chile: 'Postcode',
    Peru: 'Postcode',
    Colombia: 'Postcode',
    Venezuela: 'Postcode',
    Ecuador: 'Postcode',
    Bolivia: 'Postcode',
    Paraguay: 'Postcode',
    Uruguay: 'Postcode',
    Guyana: 'Postcode',
    Suriname: 'Postcode',
    'French Guiana': 'Postcode',
    'Falkland Islands': 'Postcode',
    Greenland: 'Postcode',
    Cuba: 'Postcode',
    Jamaica: 'Postcode',
    Haiti: 'Postcode',
    'Dominican Republic': 'Postcode',
    'Puerto Rico': 'Postcode',
    Bahamas: 'Postcode',
    Barbados: 'Postcode',
    'Trinidad and Tobago': 'Postcode',
    Grenada: 'Postcode',
    'Saint Vincent and the Grenadines': 'Postcode',
    'Saint Lucia': 'Postcode',
    'Antigua and Barbuda': 'Postcode',
    'Saint Kitts and Nevis': 'Postcode',
    Dominica: 'Postcode',
    Belize: 'Postcode',
    Guatemala: 'Postcode',
    'El Salvador': 'Postcode',
    Honduras: 'Postcode',
    Nicaragua: 'Postcode',
    'Costa Rica': 'Postcode',
    Panama: 'Postcode',
    Thailand: 'Postcode',
    Vietnam: 'Postcode',
    Cambodia: 'Postcode',
    Laos: 'Postcode',
    Myanmar: 'Postcode',
    Malaysia: 'Postcode',
    Singapore: 'Postcode',
    Indonesia: 'Postcode',
    Philippines: 'Postcode',
    Brunei: 'Postcode',
    'East Timor': 'Postcode',
    'Papua New Guinea': 'Postcode',
    Fiji: 'Postcode',
    Vanuatu: 'Postcode',
    'New Caledonia': 'Postcode',
    'Solomon Islands': 'Postcode',
    Samoa: 'Postcode',
    Tonga: 'Postcode',
    Kiribati: 'Postcode',
    Tuvalu: 'Postcode',
    Nauru: 'Postcode',
    Palau: 'Postcode',
    'Marshall Islands': 'Postcode',
    Micronesia: 'Postcode',
    'Northern Mariana Islands': 'Postcode',
    Guam: 'Postcode',
    'American Samoa': 'Postcode',
    'Cook Islands': 'Postcode',
    Niue: 'Postcode',
    Tokelau: 'Postcode',
    'Wallis and Futuna': 'Postcode',
    'French Polynesia': 'Postcode',
    Pitcairn: 'Postcode',
    'Easter Island': 'Postcode',
    'Galápagos Islands': 'Postcode',
    Bermuda: 'Postcode',
    'Cayman Islands': 'Postcode',
    'Turks and Caicos Islands': 'Postcode',
    'British Virgin Islands': 'Postcode',
    'U.S. Virgin Islands': 'Postcode',
    Anguilla: 'Postcode',
    Montserrat: 'Postcode',
    'Saint Helena': 'Postcode',
    'Ascension Island': 'Postcode',
    'Tristan da Cunha': 'Postcode',
    'South Georgia and the South Sandwich Islands': 'Postcode',
    'Bouvet Island': 'Postcode',
    'Heard Island and McDonald Islands': 'Postcode',
    'French Southern Territories': 'Postcode',
    'Svalbard and Jan Mayen': 'Postcode',
    'Åland Islands': 'Postcode',
    'Faroe Islands': 'Postcode',
    Gibraltar: 'Postcode',
    Andorra: 'Postcode',
    Russia: 'Postcode',
    Belarus: 'Postcode',
    Lithuania: 'Postcode',
    Latvia: 'Postcode',
    Estonia: 'Postcode',
    Turkey: 'Postcode',
    Ukraine: 'Postcode',
    Nigeria: 'Postcode',
    Kenya: 'Postcode',
  };

  return postalCodeLabels[countryName] || 'Postal Code';
};
