export const getRegionLabel = (countryName?: string): string => {
  if (!countryName) return 'Region';

  const countryLabels: Record<string, string> = {
    'United States': 'State',
    USA: 'State',
    US: 'State',
    Ireland: 'County',
    'United Kingdom': 'County',
    UK: 'County',
    Canada: 'Province',
    Australia: 'State',
    Germany: 'State',
    India: 'State',
    Brazil: 'State',
    Mexico: 'State',
    Argentina: 'Province',
    'South Africa': 'Province',
    Nigeria: 'State',
    Kenya: 'County',
    Japan: 'Prefecture',
    'South Korea': 'Province',
    China: 'Province',
    Russia: 'Region',
    France: 'Region',
    Italy: 'Region',
    Spain: 'Province',
    Netherlands: 'Province',
    Belgium: 'Province',
    Switzerland: 'Canton',
    Austria: 'State',
    Sweden: 'County',
    Norway: 'County',
    Denmark: 'Region',
    Finland: 'Region',
    Poland: 'Voivodeship',
    'Czech Republic': 'Region',
    Slovakia: 'Region',
    Hungary: 'County',
    Romania: 'County',
    Bulgaria: 'Province',
    Greece: 'Region',
    Portugal: 'District',
    Turkey: 'Province',
    Ukraine: 'Oblast',
    Belarus: 'Region',
    Lithuania: 'County',
    Latvia: 'Region',
    Estonia: 'County',
    Iceland: 'Region',
    'New Zealand': 'Region',
    Chile: 'Region',
    Peru: 'Region',
    Colombia: 'Department',
    Venezuela: 'State',
    Ecuador: 'Province',
    Bolivia: 'Department',
    Paraguay: 'Department',
    Uruguay: 'Department',
    Guyana: 'Region',
    Suriname: 'District',
    'French Guiana': 'Department',
    'Falkland Islands': 'Territory',
    Greenland: 'Municipality',
    Cuba: 'Province',
    Jamaica: 'Parish',
    Haiti: 'Department',
    'Dominican Republic': 'Province',
    'Puerto Rico': 'Municipality',
    Bahamas: 'District',
    Barbados: 'Parish',
    'Trinidad and Tobago': 'Region',
    Grenada: 'Parish',
    'Saint Vincent and the Grenadines': 'Parish',
    'Saint Lucia': 'District',
    'Antigua and Barbuda': 'Parish',
    'Saint Kitts and Nevis': 'Parish',
    Dominica: 'Parish',
    Belize: 'District',
    Guatemala: 'Department',
    'El Salvador': 'Department',
    Honduras: 'Department',
    Nicaragua: 'Department',
    'Costa Rica': 'Province',
    Panama: 'Province',
    Thailand: 'Province',
    Vietnam: 'Province',
    Cambodia: 'Province',
    Laos: 'Province',
    Myanmar: 'State',
    Malaysia: 'State',
    Singapore: 'District',
    Indonesia: 'Province',
    Philippines: 'Province',
    Brunei: 'District',
    'East Timor': 'District',
    'Papua New Guinea': 'Province',
    Fiji: 'Division',
    Vanuatu: 'Province',
    'New Caledonia': 'Province',
    'Solomon Islands': 'Province',
    Samoa: 'District',
    Tonga: 'Division',
    Kiribati: 'Island',
    Tuvalu: 'Island',
    Nauru: 'District',
    Palau: 'State',
    'Marshall Islands': 'Atoll',
    Micronesia: 'State',
    'Northern Mariana Islands': 'Municipality',
    Guam: 'Municipality',
    'American Samoa': 'District',
    'Cook Islands': 'Island',
    Niue: 'Village',
    Tokelau: 'Atoll',
    'Wallis and Futuna': 'District',
    'French Polynesia': 'Administrative subdivision',
    Pitcairn: 'Island',
    'Easter Island': 'Province',
    'Galápagos Islands': 'Province',
    Bermuda: 'Parish',
    'Cayman Islands': 'District',
    'Turks and Caicos Islands': 'District',
    'British Virgin Islands': 'District',
    'U.S. Virgin Islands': 'District',
    Anguilla: 'District',
    Montserrat: 'Parish',
    'Saint Helena': 'Administrative area',
    'Ascension Island': 'Administrative area',
    'Tristan da Cunha': 'Administrative area',
    'South Georgia and the South Sandwich Islands': 'Territory',
    'Bouvet Island': 'Territory',
    'Heard Island and McDonald Islands': 'Territory',
    'French Southern Territories': 'District',
    'Svalbard and Jan Mayen': 'Territory',
    'Åland Islands': 'Region',
    'Faroe Islands': 'Region',
    Gibraltar: 'Territory',
    Andorra: 'Parish',
    Monaco: 'Ward',
    Liechtenstein: 'Municipality',
    'San Marino': 'Municipality',
    'Vatican City': 'Territory',
    Malta: 'District',
    Cyprus: 'District',
    Luxembourg: 'Canton',
    Slovenia: 'Region',
    Croatia: 'County',
    'Bosnia and Herzegovina': 'Entity',
    Serbia: 'District',
    Montenegro: 'Municipality',
    'North Macedonia': 'Municipality',
    Albania: 'County',
    Kosovo: 'District',
    Moldova: 'District',
    Georgia: 'Region',
    Armenia: 'Province',
    Azerbaijan: 'District',
    Kazakhstan: 'Region',
    Uzbekistan: 'Region',
    Turkmenistan: 'Region',
    Kyrgyzstan: 'Region',
    Tajikistan: 'Region',
    Afghanistan: 'Province',
    Pakistan: 'Province',
    Nepal: 'Province',
    Bhutan: 'District',
    Bangladesh: 'Division',
    'Sri Lanka': 'Province',
    Maldives: 'Atoll',
    Mongolia: 'Province',
    'North Korea': 'Province',
    Taiwan: 'County',
    'Hong Kong': 'District',
    Macau: 'Parish',
    Israel: 'District',
    Palestine: 'Governorate',
    Jordan: 'Governorate',
    Lebanon: 'Governorate',
    Syria: 'Governorate',
    Iraq: 'Governorate',
    Iran: 'Province',
    Kuwait: 'Governorate',
    'Saudi Arabia': 'Province',
    Bahrain: 'Governorate',
    Qatar: 'Municipality',
    'United Arab Emirates': 'Emirate',
    Oman: 'Governorate',
    Yemen: 'Governorate',
    Egypt: 'Governorate',
    Libya: 'District',
    Tunisia: 'Governorate',
    Algeria: 'Province',
    Morocco: 'Province',
    'Western Sahara': 'Province',
    Mauritania: 'Region',
    Mali: 'Region',
    Niger: 'Region',
    Chad: 'Region',
    Sudan: 'State',
    'South Sudan': 'State',
    Ethiopia: 'Region',
    Eritrea: 'Region',
    Djibouti: 'Region',
    Somalia: 'Region',
    Uganda: 'District',
    Tanzania: 'Region',
    Rwanda: 'Province',
    Burundi: 'Province',
    'Democratic Republic of the Congo': 'Province',
    'Republic of the Congo': 'Department',
    'Central African Republic': 'Prefecture',
    Cameroon: 'Region',
    Gabon: 'Province',
    'Equatorial Guinea': 'Province',
    'São Tomé and Príncipe': 'Province',
    Angola: 'Province',
    Zambia: 'Province',
    Zimbabwe: 'Province',
    Botswana: 'District',
    Namibia: 'Region',
    Lesotho: 'District',
    Eswatini: 'Region',
    Madagascar: 'Province',
    Mauritius: 'District',
    Seychelles: 'District',
    Comoros: 'Island',
    Mayotte: 'Department',
    Réunion: 'Department',
    'Cape Verde': 'Municipality',
    'Guinea-Bissau': 'Region',
    Guinea: 'Region',
    'Sierra Leone': 'Province',
    Liberia: 'County',
    "Côte d'Ivoire": 'District',
    Ghana: 'Region',
    Togo: 'Region',
    Benin: 'Department',
    'Burkina Faso': 'Region',
    Gambia: 'Division',
    Senegal: 'Region',
  };

  return countryLabels[countryName] || 'Region';
};
