export const MIN_WIDTH = 76;
export const COLLAPSE_THRESHOLD = MIN_WIDTH + 10;
export const USER_INFO_COLLAPSE_THRESHOLD = 95;
export const CHEVRON_DOWN_COLLAPSE_THRESHOLD = 128;
export const NOTIFICATION_BADGE_COLLAPSE_THRESHOLD = 115;

