import { TaskKanban } from './task-kanban';
import type { Meta, StoryObj } from '@storybook/react';
import { TaskDetails } from '../../types/task';

const meta: Meta<typeof TaskKanban> = {
  title: 'Components/TaskKanban',
  component: TaskKanban,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: `
A sophisticated kanban board component designed for agricultural task management and workflow visualization.

## Component Overview

The TaskKanban component provides a comprehensive kanban board interface for managing
agricultural tasks with drag-and-drop functionality, status-based organization, and
visual workflow tracking optimized for farm management operations.

## Key Features
- **Drag-and-drop interface**: Intuitive task movement between status columns
- **Status-based organization**: Clear visual separation of task stages
- **Task cards**: Detailed information display for each agricultural task
- **Real-time updates**: Dynamic status changes and progress tracking
- **Agricultural focus**: Optimized for farm task management workflows
- **Responsive design**: Adapts to different screen sizes and devices

## Interface Elements
- **Status columns**: Visual containers for different task stages
- **Task cards**: Individual task information with details and actions
- **Drag handles**: Interactive elements for task movement
- **Status indicators**: Visual cues for task progress and priority
- **Progress tracking**: Completion status and timeline information

## Usage Examples
- Soil sampling project management
- Crop monitoring workflow tracking
- Equipment maintenance scheduling
- Harvest planning and coordination
- Team task assignment and oversight
- Agricultural project status monitoring
        `,
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    tasks: {
      control: 'object',
      description:
        'Array of task objects with status and agricultural information',
      table: {
        type: { summary: 'TaskDetails[]' },
      },
    },
    onUpdatePriority: {
      action: 'priority updated',
      description: 'Callback when task priority is updated',
    },
    onUpdateStatus: {
      action: 'status updated',
      description: 'Callback when task status is updated',
    },
    onAcceptTask: {
      action: 'task accepted',
      description: 'Callback when task is accepted',
    },
    onDeclineTask: {
      action: 'task declined',
      description: 'Callback when task is declined',
    },
    onDeleteTask: {
      action: 'task deleted',
      description: 'Callback when task is deleted',
    },
  },
  args: {
    tasks: [],
  },
};

export default meta;
type Story = StoryObj<typeof TaskKanban>;

const mockTasks: TaskDetails[] = [
  {
    id: '1',
    organisation_name: 'GreenFields Cooperative',
    organisation_id: 1,
    assigned_to_organisation: 1,
    farmer_name: 'Soil sampling - Field 1',
    assigned_to: 1,
    task_creator: 1,
    farmer_organisation_id: 1,
    task_type: 'Soil Sampler',
    farms: 'Field 1, Field 2',
    lab: 'Agricultural Testing Lab',
    no_of_samples: 25,
    farmer_address: '123 Rural Route 7, Farmville, IA 50235',
    soil_sampler: 'Sarah Wilson',
    farmteam_task_number: 'FT-120',
    id_number: 120,
    task_has_not_started_test: false,
    task_has_unmatched_samples: false,
    task_has_tests_without_lab_result: true,
    date: '2024-06-16',
    complete_by: '2024-06-25',
    status: 'pending',
    tests: [],
    created_by: 1,
    issues_approve_by: null,
    reporting_status: 'Pending lab results',
    combine_task_report: 0,
    combine_soil_analysis_report: 0,
    advisor: 'Dr. Emily Brown',
  },
  {
    id: '2',
    organisation_name: 'WheatGrowers Association',
    organisation_id: 1,
    assigned_to_organisation: 1,
    farmer_name: 'Fertilizer application - Wheat field',
    assigned_to: 1,
    task_creator: 1,
    farmer_organisation_id: 1,
    task_type: 'Fertilizer application',
    farms: 'Field 3',
    lab: 'Crop Health Lab',
    no_of_samples: 15,
    farmer_address: '456 County Road 12, Wheatland, KS 67890',
    soil_sampler: 'David Thompson',
    farmteam_task_number: 'FT-121',
    id_number: 121,
    task_has_not_started_test: false,
    task_has_unmatched_samples: false,
    task_has_tests_without_lab_result: false,
    date: '2024-06-15',
    complete_by: '2024-06-20',
    status: 'in_progress',
    tests: [],
    created_by: 1,
    issues_approve_by: null,
    reporting_status: 'Application in progress',
    combine_task_report: 0,
    combine_soil_analysis_report: 0,
    advisor: 'Dr. Lisa Garcia',
  },
  {
    id: '3',
    organisation_name: 'Corn Belt Cooperative',
    organisation_id: 1,
    assigned_to_organisation: 1,
    farmer_name: 'Corn harvest - Field 4',
    assigned_to: 1,
    task_creator: 1,
    farmer_organisation_id: 1,
    task_type: 'Harvest',
    farms: 'Field 4',
    lab: 'Harvest Planning Lab',
    no_of_samples: 20,
    farmer_address: '789 Harvest Lane, Cornfield, IL 60001',
    soil_sampler: 'Mike Rodriguez',
    farmteam_task_number: 'FT-123',
    id_number: 123,
    task_has_not_started_test: false,
    task_has_unmatched_samples: false,
    task_has_tests_without_lab_result: false,
    date: '2024-06-10',
    complete_by: '2024-06-15',
    status: 'completed',
    tests: [],
    created_by: 1,
    issues_approve_by: null,
    reporting_status: 'Harvest completed successfully',
    combine_task_report: 1,
    combine_soil_analysis_report: 1,
    advisor: 'Dr. James Wilson',
  },
  {
    id: '4',
    organisation_name: 'Water Management Group',
    organisation_id: 1,
    assigned_to_organisation: 1,
    farmer_name: 'Irrigation system maintenance',
    assigned_to: 1,
    task_creator: 1,
    farmer_organisation_id: 1,
    task_type: 'Drainage inspection',
    farms: 'Irrigation Zone 1',
    lab: 'Water Quality Lab',
    no_of_samples: 8,
    farmer_address: '987 Water Way, Irrigation Valley, CA 90001',
    soil_sampler: 'Thomas Anderson',
    farmteam_task_number: 'FT-124',
    id_number: 124,
    task_has_not_started_test: true,
    task_has_unmatched_samples: false,
    task_has_tests_without_lab_result: false,
    date: '2024-06-18',
    complete_by: '2024-06-22',
    status: 'pending',
    tests: [],
    created_by: 1,
    issues_approve_by: null,
    reporting_status: 'Scheduled for maintenance',
    combine_task_report: 0,
    combine_soil_analysis_report: 0,
    advisor: 'Dr. Patricia Chen',
  },
  {
    id: '5',
    organisation_name: 'Organic Farmers Alliance',
    organisation_id: 1,
    assigned_to_organisation: 1,
    farmer_name: 'Organic certification audit',
    assigned_to: 1,
    task_creator: 1,
    farmer_organisation_id: 1,
    task_type: 'Others',
    farms: 'Organic Farm A',
    lab: 'Organic Certification Lab',
    no_of_samples: 12,
    farmer_address: '555 Organic Drive, Natural City, OR 97001',
    soil_sampler: 'Rachel Green',
    farmteam_task_number: 'FT-125',
    id_number: 125,
    task_has_not_started_test: false,
    task_has_unmatched_samples: false,
    task_has_tests_without_lab_result: false,
    date: '2024-06-12',
    complete_by: '2024-06-18',
    status: 'in_progress',
    tests: [],
    created_by: 1,
    issues_approve_by: null,
    reporting_status: 'Audit in progress',
    combine_task_report: 0,
    combine_soil_analysis_report: 0,
    advisor: 'Dr. Organic',
  },
];

export const Default: Story = {
  args: {
    tasks: mockTasks,
  },
  parameters: {
    docs: {
      description: {
        story:
          'Standard kanban board with multiple agricultural tasks across different status columns including soil sampling, fertilizer application, harvest, irrigation maintenance, and organic certification.',
      },
    },
  },
};

export const Empty: Story = {
  args: {
    tasks: [],
  },
  parameters: {
    docs: {
      description: {
        story:
          'Empty kanban board showing the initial state when no tasks are available, demonstrating the component structure and layout.',
      },
    },
  },
};

export const SoilSamplingWorkflow: Story = {
  args: {
    tasks: [
      {
        id: '1',
        organisation_name: 'Soil Analysis Co-op',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Field 1 - Initial sampling',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Soil Sampler',
        farms: 'Field 1',
        lab: 'Agricultural Testing Lab',
        no_of_samples: 30,
        farmer_address: '123 Rural Route 7, Farmville, IA 50235',
        soil_sampler: 'Sarah Wilson',
        farmteam_task_number: 'FT-201',
        id_number: 201,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: true,
        date: '2024-06-20',
        complete_by: '2024-06-25',
        status: 'pending',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Scheduled for sampling',
        combine_task_report: 0,
        combine_soil_analysis_report: 0,
        advisor: 'Dr. Emily Brown',
      },
      {
        id: '2',
        organisation_name: 'Soil Analysis Co-op',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Field 2 - Core sampling',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Soil Sampler',
        farms: 'Field 2',
        lab: 'Agricultural Testing Lab',
        no_of_samples: 25,
        farmer_address: '456 County Road 12, Wheatland, KS 67890',
        soil_sampler: 'David Thompson',
        farmteam_task_number: 'FT-202',
        id_number: 202,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: true,
        date: '2024-06-19',
        complete_by: '2024-06-24',
        status: 'in_progress',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Samples collected, sent to lab',
        combine_task_report: 0,
        combine_soil_analysis_report: 0,
        advisor: 'Dr. Lisa Garcia',
      },
      {
        id: '3',
        organisation_name: 'Soil Analysis Co-op',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Field 3 - Analysis complete',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Soil Sampler',
        farms: 'Field 3',
        lab: 'Agricultural Testing Lab',
        no_of_samples: 20,
        farmer_address: '789 Harvest Lane, Cornfield, IL 60001',
        soil_sampler: 'Mike Rodriguez',
        farmteam_task_number: 'FT-203',
        id_number: 203,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: false,
        date: '2024-06-15',
        complete_by: '2024-06-20',
        status: 'completed',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Analysis complete, report generated',
        combine_task_report: 1,
        combine_soil_analysis_report: 1,
        advisor: 'Dr. James Wilson',
      },
    ],
  },
  parameters: {
    docs: {
      description: {
        story:
          'Soil sampling workflow with tasks in different stages: pending initial sampling, in-progress core sampling, and completed analysis with report generation.',
      },
    },
  },
};

export const CropMonitoringWorkflow: Story = {
  args: {
    tasks: [
      {
        id: '1',
        organisation_name: 'Crop Health Monitoring',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Wheat field - Growth monitoring',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Crop monitoring',
        farms: 'Wheat Field A',
        lab: 'Crop Health Lab',
        no_of_samples: 15,
        farmer_address: '123 Rural Route 7, Farmville, IA 50235',
        soil_sampler: 'Emily Davis',
        farmteam_task_number: 'FT-301',
        id_number: 301,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: true,
        date: '2024-06-22',
        complete_by: '2024-06-28',
        status: 'pending',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Scheduled for monitoring',
        combine_task_report: 0,
        combine_soil_analysis_report: 0,
        advisor: 'Dr. Emily Brown',
      },
      {
        id: '2',
        organisation_name: 'Crop Health Monitoring',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Corn field - Disease assessment',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Crop monitoring',
        farms: 'Corn Field B',
        lab: 'Crop Health Lab',
        no_of_samples: 12,
        farmer_address: '456 County Road 12, Wheatland, KS 67890',
        soil_sampler: 'Lisa Garcia',
        farmteam_task_number: 'FT-302',
        id_number: 302,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: false,
        date: '2024-06-20',
        complete_by: '2024-06-25',
        status: 'in_progress',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Assessment in progress',
        combine_task_report: 0,
        combine_soil_analysis_report: 0,
        advisor: 'Dr. Lisa Garcia',
      },
      {
        id: '3',
        organisation_name: 'Crop Health Monitoring',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Soybean field - Health report',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Crop monitoring',
        farms: 'Soybean Field C',
        lab: 'Crop Health Lab',
        no_of_samples: 18,
        farmer_address: '789 Harvest Lane, Cornfield, IL 60001',
        soil_sampler: 'James Wilson',
        farmteam_task_number: 'FT-303',
        id_number: 303,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: false,
        date: '2024-06-18',
        complete_by: '2024-06-22',
        status: 'completed',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Health assessment complete',
        combine_task_report: 1,
        combine_soil_analysis_report: 1,
        advisor: 'Dr. James Wilson',
      },
    ],
  },
  parameters: {
    docs: {
      description: {
        story:
          'Crop monitoring workflow with wheat growth monitoring, corn disease assessment, and completed soybean health reporting for comprehensive agricultural oversight.',
      },
    },
  },
};

export const EquipmentMaintenanceWorkflow: Story = {
  args: {
    tasks: [
      {
        id: '1',
        organisation_name: 'Farm Equipment Co-op',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Tractor maintenance - Engine service',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Equipment maintenance',
        farms: 'Equipment Bay 1',
        lab: 'Equipment Service Center',
        no_of_samples: 0,
        farmer_address: '321 Farm Road, Equipment City, TX 75001',
        soil_sampler: 'Carlos Martinez',
        farmteam_task_number: 'FT-401',
        id_number: 401,
        task_has_not_started_test: true,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: false,
        date: '2024-06-25',
        complete_by: '2024-06-30',
        status: 'pending',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Scheduled for service',
        combine_task_report: 0,
        combine_soil_analysis_report: 0,
        advisor: 'Carlos Martinez',
      },
      {
        id: '2',
        organisation_name: 'Farm Equipment Co-op',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Irrigation pump repair',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Equipment maintenance',
        farms: 'Irrigation Station 2',
        lab: 'Equipment Service Center',
        no_of_samples: 0,
        farmer_address: '654 Water Way, Irrigation Valley, CA 90001',
        soil_sampler: 'Maria Gonzalez',
        farmteam_task_number: 'FT-402',
        id_number: 402,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: false,
        date: '2024-06-23',
        complete_by: '2024-06-28',
        status: 'in_progress',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Repair in progress',
        combine_task_report: 0,
        combine_soil_analysis_report: 0,
        advisor: 'Maria Gonzalez',
      },
      {
        id: '3',
        organisation_name: 'Farm Equipment Co-op',
        organisation_id: 1,
        assigned_to_organisation: 1,
        farmer_name: 'Harvester calibration',
        assigned_to: 1,
        task_creator: 1,
        farmer_organisation_id: 1,
        task_type: 'Equipment maintenance',
        farms: 'Equipment Bay 3',
        lab: 'Equipment Service Center',
        no_of_samples: 0,
        farmer_address: '987 Harvest Lane, Cornfield, IL 60001',
        soil_sampler: 'Thomas Anderson',
        farmteam_task_number: 'FT-403',
        id_number: 403,
        task_has_not_started_test: false,
        task_has_unmatched_samples: false,
        task_has_tests_without_lab_result: false,
        date: '2024-06-20',
        complete_by: '2024-06-25',
        status: 'completed',
        tests: [],
        created_by: 1,
        issues_approve_by: null,
        reporting_status: 'Calibration complete',
        combine_task_report: 1,
        combine_soil_analysis_report: 0,
        advisor: 'Thomas Anderson',
      },
    ],
  },
  parameters: {
    docs: {
      description: {
        story:
          'Equipment maintenance workflow with scheduled tractor service, in-progress irrigation pump repair, and completed harvester calibration for farm equipment management.',
      },
    },
  },
};
